version: "3.9"
name: choku
services:
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: choku
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./choku-data/:/choku-data/
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./sql/populate-tables.sql:/docker-entrypoint-initdb.d/populate-tables.sql
